language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - nightly

before_script:
 - travis_retry composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis